defaults: &defaults  
  working_directory: ~/repo  
version: 2  
jobs:  
  build:  
    <<: *defaults  
  docker:  
      - image: circleci/ruby:2.6  
    environment:  
    steps:  
      - checkout  
      - run:  
          name: Bundler Install  
          command: gem install bundler  
      - run:  
          name: Rsync Install  
          command: sudo apt install rsync  
      - run:  
          name: Install Dependencies  
          command: bundle install  
      - run:  
          name: Jekyll build  
          command: bundle exec jekyll build  
workflows:  
  version: 2  
  build:  
    jobs:  
      - build