version: 2.1

jobs:
  run_pytest:
    docker:
      - image: continuumio/miniconda3
    working_directory: /tmp/src/NBCLab.github.io
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            conda create -n py36_env python=3.6 numpy pytest matplotlib -yq
            source activate py36_env
            pytest /tmp/src/NBCLab.github.io
workflows:
  version: 2.1
  build:
    jobs:
      - run_pytest
