name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Build the site in the jekyll/builder container
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"

  linkchecker:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Set up Rubygems, Bundler, jekyll
        run: |
          gem update --system --no-document
          gem update bundler --no-document
          gem install jekyll bundler
          bundle install

      - name: Build jekyll website with drafts
        run: bundle exec jekyll build --drafts

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.0.8
        with:
          args: --verbose --no-progress _site/**/*.md _site/**/*.html
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
