name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Build the site in the jekyll/builder container
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"

      - name: Archive build files
        uses: actions/upload-artifact@v2
        with:
          name: build_files
          path: ${{ github.workspace }}/_site/

  linkchecker:

    runs-on: ubuntu-latest

    steps:
      - name: Download build files
        uses: actions/download-artifact@v2
        with:
          name: build_files

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.0.8
        with:
          args: --verbose --no-progress ${{ github.workspace }}/_site/**/*.md ${{ github.workspace }}/_site/**/*.html
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
